#!/bin/bash

#python3 ./search-compare.py > table

gnuplot -persist << EOF
set term svg size 800,600
set output "search-compare.svg"
set title "Binary Search Performance"
set ylabel "Compares Per Search"
set xlabel "Array Size"
set logscale x 2
set xtics 2
set key left top
plot "table" using 1:2 with lines title columnheader(2),\
 "table" using 1:3 with lines title columnheader(3),\
 "table" using 1:4 with lines title columnheader(4),\
 "table" using 1:5 with lines title columnheader(5),\
 "table" using 1:6 with lines title columnheader(6)
EOF
