#!/bin/bash

python3 ./search-compare.py > table

gnuplot -persist << EOF
set ylabel "compares"
set xlabel "size"
plot "table" using 1:2 with lines title columnheader(2),\
 "table" using 1:3 with lines title columnheader(3),\
 "table" using 1:4 with lines title columnheader(4),\
 "table" using 1:5 with lines title columnheader(5),\
 "table" using 1:6 with lines title columnheader(6)
EOF
