#!/bin/bash

#python3 ./search-compare.py > table

LINEWIDTH=1

gnuplot -persist << EOF
set term svg size 800,600
set output "search-compare.svg"
set title "Binary Search Performance"
set ylabel "Compares Per Search"
set xlabel "Array Size"
set logscale x 2
set xtics 2
set key left top
set style line 1 linewidth $LINEWIDTH
set style line 2 linewidth $LINEWIDTH
set style line 3 linewidth $LINEWIDTH
set style line 4 linewidth $LINEWIDTH
set style line 5 linewidth $LINEWIDTH dashtype 3
set style line 6 linewidth $LINEWIDTH dashtype 3
plot "table" using 1:2 with lines title columnheader(2) ls 1,\
 "table" using 1:3 with lines title columnheader(3) ls 2,\
 "table" using 1:4 with lines title columnheader(4) ls 3,\
 "table" using 1:5 with lines title columnheader(5) ls 4,\
 "table" using 1:6 with lines title columnheader(6) ls 5,\
 "table" using 1:7 with lines title columnheader(7) ls 6
EOF

gnuplot -persist << EOF
set term pdfcairo noenhanced font "Frutiger LT Std,12"
set output "search-compare.pdf"
set title "Binary Search Performance"
set ylabel "Compares Per Search"
set xlabel "Array Size"
set logscale x 2
set xtics 2
set key left top
set style line 1 linewidth $LINEWIDTH linetype 1
set style line 2 linewidth $LINEWIDTH linetype 2
set style line 3 linewidth $LINEWIDTH linetype 3
set style line 4 linewidth $LINEWIDTH linetype 4
set style line 5 linewidth $LINEWIDTH dashtype 3 linetype 1
set style line 6 linewidth $LINEWIDTH dashtype 3 linetype 2
plot "table" using 1:2 with lines title columnheader(2) ls 1,\
 "table" using 1:3 with lines title columnheader(3) ls 2,\
 "table" using 1:4 with lines title columnheader(4) ls 3,\
 "table" using 1:5 with lines title columnheader(5) ls 4,\
 "table" using 1:6 with lines title columnheader(6) ls 5,\
 "table" using 1:7 with lines title columnheader(7) ls 6
EOF
